### ISSUE TITLE
Initializing database() failed

### ISSUE THREAD

**Issue by dspautz** [coleifer/walrus#102]
Python 3.7.4
walrus 0.8.0
redis 3.3.8

```python
from walrus import Database
Database()
```

> Traceback (most recent call last):
>  File "src/main.py", line 70, in <module>
>    main = Main(parser.parse_args())
>  File "src/main.py", line 21, in __init__
>    Database()
>  File "/home/user/projects/org/QubicAgent/lib64/python3.7/site-packages/walrus/database.py", line 80, in __init__
>    self.init_scripts(script_dir=script_dir)
>  File "/home/user/projects/org/QubicAgent/lib64/python3.7/site-packages/walrus/database.py", line 146, in init_scripts
>    script_obj = self.register_script(fh.read())
AttributeError: 'Database' object has no attribute 'register_script'

I found out, that at this line of code the self.register_script method does not exist. Not in your whole source code.

I am confused

**Comment by dspautz** [comment]
Solved. It was not a problem with your code
