### ISSUE TITLE
WRONGTYPE Operation when trying to get Hash using get_key

### ISSUE THREAD

**Issue by pomo-mondreganto** [coleifer/walrus#120]
Documentation states that if I try to get a Hash key using the `db.get_key` function I should get Hash object in return. But in the following example: 

```
>>> import walrus
>>> db = walrus.Walrus()
>>> h = db.Hash('test')
>>> h['123'] = 123
>>> db.get_key('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/dirty_3.7/lib/python3.7/site-packages/walrus/database.py", line 199, in get_key
    return self.__mapping.get(self.type(key), self.__getitem__)(key)
  File "/usr/local/anaconda3/envs/dirty_3.7/lib/python3.7/site-packages/redis/client.py", line 1339, in __getitem__
    value = self.get(name)
  File "/usr/local/anaconda3/envs/dirty_3.7/lib/python3.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/usr/local/anaconda3/envs/dirty_3.7/lib/python3.7/site-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/anaconda3/envs/dirty_3.7/lib/python3.7/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/usr/local/anaconda3/envs/dirty_3.7/lib/python3.7/site-packages/redis/connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

I get an exception. `walrus` version is 0.8.0.

**Comment by coleifer** [comment]
You've got a hash there and you're using the "get string key". Read the Redis docs, it describes this:

https://redis.io/commands/get

**Comment by Frank5000** [comment]
To clarify, if `get_key()` only works for keys for strings, what exactly do the docs mean by
`Return a rich object for the given key. For instance, if a hash key is requested, then a Hash will be returned.`

**Comment by coleifer** [comment]
FML I think the mapping wasn't working because it wasn't upgraded for python 3 and wasn't covered in tests. You're both correct and I was mistaken about how this is supposed to behave.

Working up a fix.

**Comment by coleifer** [comment]
Thanks @Frank5000 and my apologies @pomo-mondreganto - this is now fixed in master.
