### ISSUE TITLE
Database' object has no attribute 'register_script'

### ISSUE THREAD

**Issue by sdave2** [coleifer/walrus#135]
In a different pip-venv, the commands works completely fine. In my current venv, I am getting this error.

```
Python 3.8.2 (default, Feb 26 2020, 14:58:38) 
Redis: 3.5.3
walrus: 0.8.1
```

Command_1:
```
>>> from walrus import Database
>>> db = Database()
```

Error_1:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/walrus/database.py", line 80, in __init__
    self.init_scripts(script_dir=script_dir)
  File "/usr/local/lib/python3.8/site-packages/walrus/database.py", line 146, in init_scripts
    script_obj = self.register_script(fh.read())
AttributeError: 'Database' object has no attribute 'register_script'
```

Command_2:
```
>>> db = Database(host="0.0.0.0", port=6379, password='pass1234')
```

Error_2:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/walrus/database.py", line 72, in __init__
    super(Database, self).__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

Pip Freeze:

```
appdirs==1.4.4
attrs==20.3.0
certifi==2020.12.5
chardet==3.0.4
dataspec==0.3.2
distlib==0.3.1
elasticsearch==7.10.1
filelock==3.0.12
idna==2.10
iniconfig==1.1.1
packaging==20.8
pipenv==2020.11.15
pluggy==0.13.1
py==1.10.0
pyparsing==2.4.7
pytest==6.2.1
redis==3.5.3
requests==2.25.0
robot-xml-parser==0.0.1
robotframework==3.2.2
six==1.15.0
stringcase==1.2.0
toml==0.10.2
urllib3==1.26.2
virtualenv==20.2.2
virtualenv-clone==0.5.4
walrus==0.8.1

```

**Comment by sdave2** [comment]
I see an issue similar to this has been created and closed earlier. 
https://github.com/coleifer/walrus/issues/102


I am using the new version of walrus (0.8.1)

**Comment by coleifer** [comment]
You do not seem to have `redis` installed in your environment.

I just created a new virtualenv:

```
pip install walrus redis
Collecting redis
  Using cached redis-3.5.3-py2.py3-none-any.whl (72 kB)
Collecting walrus
  Downloading walrus-0.8.1.tar.gz (80 kB)
...
Installing collected packages: redis, walrus
Successfully installed redis-3.5.3 walrus-0.8.1
```

Showing pip freeze:

```
$ pip freeze
redis==3.5.3
walrus==0.8.1
```

Works fine:

```python
>>> from walrus import Database
>>> db = Database()
>>> type(db.register_script)
<class 'method'>
```

**Comment by sdave2** [comment]
if you check my pip freeze, i do have redis installed.

**Comment by sdave2** [comment]
pytest==6.2.1
redis==3.5.3
requests==2.25.0
robot-xml-parser==0.0.1
robotframework==3.2.2

**Comment by sdave2** [comment]
also, it works in another virtual venv, but not in this one. The current one I am testing is in a docker container.

**Comment by coleifer** [comment]
>also, it works in another virtual venv, but not in this one

Then why would you assume this is a bug in walrus? Put some print statements in there and see if redis is importable. Do you have your own module named `redis.py` that is shadowing the one you installed? Honestly bro.

**Comment by sdave2** [comment]
shoot. I do have a module named `redis.py`.
That could be what is overshadowing the original redis module.

My bad.
