### ISSUE TITLE
KeyError on Model fields that aren't secondary indexes.

### ISSUE THREAD

**Issue by johndlong** [coleifer/walrus#46]
If we create an instance of a Model that doesn't specify a field (and that field is not part of a secondary index), should the behavior be for that attribute to return None on access?

Getting KeyError in this case is a bit unexpected.

```
>>> from walrus import *
>>> db = Database()
>>> class Foo(Model):
...     name = TextField(primary_key=True)
...     keyerror = TextField()
...
test>>> test = Foo(name='test')
>>> test.name
'test'
>>> test.keyerror
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\walrus\models.py", line 123, in __get__
    return instance._data[self.name]
KeyError: 'keyerror'
```

**Comment by coleifer** [comment]
Seems like a bug , I'll get it fixed shortly.

**Comment by johndlong** [comment]
Ok, so I screwed up my example a bit (didn't actually use the create method to generate it).  Here is a better set of reproduction instructions:

For further clarification, it looks like the issue only comes up with an instance that is 'created'.  A subsequent loaded instance of the object works just fine.

```
>>> from walrus import *
>>> db = Database()
>>> class Foo(Model):
...     database = db
...     name = TextField(primary_key=True)
...     keyerror = TextField()
...
>>> test = Foo.create(name='foo')
>>> test.name
'foo'
>>> test.keyerror
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Envs\venv\lib\site-packages\walrus-0.3.4-py2.7.egg\walrus\models.py", line 123, in __get__
    return instance._data[self.name]
KeyError: 'keyerror'
>>> test2 = Foo.load('foo')
>>> test2.name
u'foo'
>>> test2.keyerror
```
