### ISSUE TITLE
Query searching for boolean and integer

### ISSUE THREAD

**Issue by luisdemarchi** [coleifer/walrus#54]
If I search for a particular integer field, I get results. If I search for a Boolean field, I also get it. But if I try to join the two queries the return is a mistake.

 ```
#Presence REDIS DB (no-SQL)
db = walrus.Database(host='localhost', port=6379, db=0)

class Presence(walrus.Model):
    __database__ = db
    channel_name = walrus.TextField(primary_key=True)
    is_accessible = walrus.BooleanField(index=True, default=False)
    state = walrus.IntegerField(default=MatchState.CLOSED.value, index=True)

>>> Presence.query(Presence.is_accessible == True).__next__()
<Presence: defaultuaGTz>

>>> Presence.query(Presence.state == 4).__next__()
<Presence: defaultuaGTz>

>>> Presence.query(Presence.state == 4 & Presence.is_accessible == True).__next__()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Volumes/MacHD/Users/Git/projectXYZ/.env/lib/python3.6/site-packages/walrus/models.py", line 819, in query
    result = executor.execute(expression)
  File "/Volumes/MacHD/Users/Git/projectXYZ/.env/lib/python3.6/site-packages/walrus/query.py", line 240, in execute
    return self._mapping[op](expression.lhs, expression.rhs)
  File "/Volumes/MacHD/Users/Git/projectXYZ/.env/lib/python3.6/site-packages/walrus/query.py", line 243, in execute_eq
    index = lhs.get_index(OP_EQ)
AttributeError: 'Expression' object has no attribute 'get_index'
```

**Comment by luisdemarchi** [comment]
I believe I have found the solution, I will respond. Please correct me if there is a more beautiful way.

```
>>> Presence.query((Presence.state == 4) & (Presence.is_accessible == True)).__next__()
<Presence: defaultuaGTz>
```
