### ISSUE TITLE
AttributeError: 'int' object has no attribute 'lower'

### ISSUE THREAD

**Issue by samos123** [coleifer/walrus#66]
re-running with more debugging enabled to see why it only happens for 1 of the entries

```
Traceback (most recent call last):                                                                                                             File "redis_indexer.py", line 21, in <module>
    populate_index()
  File "redis_indexer.py", line 18, in populate_index
    ac.store(obj_id=product['sku'], title=product['name'])
  File "/root/open-data-set/.venv/lib/python3.6/site-packages/walrus/autocomplete.py", line 136, in store
    clean_title = ' '.join(self.tokenize_title(title))
  File "/root/open-data-set/.venv/lib/python3.6/site-packages/walrus/autocomplete.py", line 60, in tokenize_title
    phrase = re.sub('[^a-z0-9_\-\s]', '', phrase.lower())
AttributeError: 'int' object has no attribute 'lower'
```

**Comment by samos123** [comment]
Looks like the issue was because one of the entires had title=None.
