### ISSUE TITLE
SyntaxError: invalid syntax while installing the package

### ISSUE THREAD

**Issue by rakeshgunduka** [coleifer/walrus#71]
Command used - `pip install walrus`

    Collecting walrus
        Using cached https://files.pythonhosted.org/packages/d7/51/3731ff39c5ac34cacde065fc39630c28693e01bd73800fd76e83460a9840/walrus-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nq/s1v8_zm95tl49hc318m0y4l00000gn/T/pip-install-rqhukbv7/walrus/setup.py", line 17, in <module>
        version=__import__('walrus').__version__,
      File "/private/var/folders/nq/s1v8_zm95tl49hc318m0y4l00000gn/T/pip-install-rqhukbv7/walrus/walrus/__init__.py", line 34, in <module>
        from walrus.database import Database
      File "/private/var/folders/nq/s1v8_zm95tl49hc318m0y4l00000gn/T/pip-install-rqhukbv7/walrus/walrus/database.py", line 269
        def listener(self, channels=None, patterns=None, async=False):
                                                             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/nq/s1v8_zm95tl49hc318m0y4l00000gn/T/pip-install-rqhukbv7/walrus/
Please let me know if I am missing something.

**Comment by coleifer** [comment]
This was fixed in 8976248446fef5d4db0a6df23160056dc40d6ad0. I've tagged a new release, 0.5.2, which contains the fix.

**Comment by rakeshgunduka** [comment]
Thanks @coleifer 
Keep up good work
