### ISSUE TITLE
error when installing on ubuntu 16.04

### ISSUE THREAD

**Issue by hc000** [coleifer/walrus#73]
$ pip install walrus
Collecting walrus
  Downloading https://files.pythonhosted.org/packages/da/75/ec68a3a9ae57395cfb37ce6056181e5ced92f54e26e900df8ee72140ad30/walrus-0.6.3.tar.gz
 (78kB)
    100% |████████████████████████████████| 81kB 3.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-87Pfj8/walrus/setup.py", line 17, in <module>
        version=__import__('walrus').__version__,
      File "/tmp/pip-build-87Pfj8/walrus/walrus/__init__.py", line 37, in <module>
        from walrus.database import Database
      File "/tmp/pip-build-87Pfj8/walrus/walrus/database.py", line 68, in <module>
        class Database(Redis):
      File "/tmp/pip-build-87Pfj8/walrus/walrus/database.py", line 72, in Database
        RESPONSE_CALLBACKS = Redis.RESPONSE_CALLBACKS
    AttributeError: type object 'object' has no attribute 'RESPONSE_CALLBACKS'

**Comment by coleifer** [comment]
pip install redis

I'll patch but that's all you need to fix it.

**Comment by coleifer** [comment]
Fixed and pushed a new release, 0.6.4.
