### ISSUE TITLE
AttributeError: type object 'object' has no attribute 'RESPONSE_CALLBACKS' while installing

### ISSUE THREAD

**Issue by rakeshgunduka** [coleifer/walrus#74]
Collecting walrus (from portale->-r pip-requirements.txt (line 43))
      Downloading https://files.pythonhosted.org/packages/da/75/ec68a3a9ae57395cfb37ce6056181e5ced92f54e26e900df8ee72140ad30/walrus-0.6.3.tar.gz (78kB)
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-oqwfpcuq/walrus/setup.py", line 17, in <module>
            version=__import__('walrus').__version__,
          File "/tmp/pip-install-oqwfpcuq/walrus/walrus/__init__.py", line 37, in <module>
            from walrus.database import Database
          File "/tmp/pip-install-oqwfpcuq/walrus/walrus/database.py", line 68, in <module>
            class Database(Redis):
          File "/tmp/pip-install-oqwfpcuq/walrus/walrus/database.py", line 72, in Database
            RESPONSE_CALLBACKS = Redis.RESPONSE_CALLBACKS
        AttributeError: type object 'object' has no attribute 'RESPONSE_CALLBACKS'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oqwfpcuq/walrus/

**Comment by coleifer** [comment]
pip install redis

**Comment by rakeshgunduka** [comment]
@coleifer That worked, my bad.

**Comment by coleifer** [comment]
I've fixed the code so that the setup script will work if redis isn't installed already. It will be installed automatically as it's a dependency.

**Comment by coleifer** [comment]
0.6.4

**Comment by rakeshgunduka** [comment]
Thanks @coleifer
