### ISSUE TITLE
Package require missing - redis

### ISSUE THREAD

**Issue by HansBug** [coleifer/walrus#96]
Firstly, I used the pip package to build a simple model, but it show me

```text
Traceback (most recent call last):
  File "test_walrus.py", line 21, in <module>
    _user.save()
  File "/usr/local/lib/python3.5/dist-packages/walrus/models.py", line 875, in save
    index.save(self)
  File "/usr/local/lib/python3.5/dist-packages/walrus/models.py", line 406, in save
    self.store_instance(key, instance, value)
  File "/usr/local/lib/python3.5/dist-packages/walrus/models.py", line 443, in store_instance
    key[instance.get_hash_id()] = value
  File "/usr/local/lib/python3.5/dist-packages/walrus/containers.py", line 614, in __setitem__
    return self.database.zadd(self.key, {item: score})
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2275, in zadd
    raise RedisError("ZADD requires an equal number of "
redis.exceptions.RedisError: ZADD requires an equal number of values and scores
```

python version is `3.5.2`，walrus version is `3.2.1`，redis(both client and server) is `3.0.6`

Now the version of pip package `redis` is `3.2.1`.

Then I just upgraded the package `redis` to `3.3.7`(the newest version when submit this issue), it worked well.

I think that maybe this package version requirement should be added in order to make sure that the package can run properly(maybe in the old version of package `redis` there are difference in the api? maybe, but I don't know the detail)

Here is the simple script I locally used

```python
from walrus import *

db = Database()


class User(Model):
    __database__ = db
    name = TextField(primary_key=True)
    created_at = DateTimeField(index=True)

    def _before_save(self):
        self.created_at = self.created_at or datetime.datetime.now()

    def save(self):
        self._before_save()
        Model.save(self)


if __name__ == "__main__":
    _user = User(name="emmmwhatisthename")
    _user.save()

    print(_user)
    print(_user.created_at)
    print(_user.to_hash())
    print(_user.get_hash_id())
    print(_user.get_id())
```

**Comment by coleifer** [comment]
I don't think this is correct, as I'm pretty sure nothing has changed. Perhaps you've incorrectly reported the installed versions you have.

https://github.com/andymccurdy/redis-py/blob/master/CHANGES
